# Generated by Django 3.2.13 on 2022-04-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='send_advertising',
            field=models.BooleanField(default=False, verbose_name='Consent to send advertising'),
        ),
    ]
