# Generated by Django 3.2.13 on 2022-04-25 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_send_advertising'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Category')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Genre')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='MusicProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title music')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='Slug')),
                ('file', models.FileField(upload_to='tracks/', verbose_name='File')),
                ('author', models.CharField(max_length=255, verbose_name='Author')),
                ('image', models.ImageField(upload_to='img_tracks/', verbose_name='Imagine')),
                ('description', models.TextField(null=True, verbose_name='Track description')),
                ('status_track', models.CharField(choices=[('P', 'Posted'), ('NP', 'Not posted')], max_length=255, verbose_name='Status track')),
                ('data_added', models.DateField(auto_now_add=True, verbose_name='Date added')),
                ('all_genre', models.ManyToManyField(to='core.Genre', verbose_name='All genre')),
                ('track_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='Track category')),
            ],
        ),
    ]
