# Generated by Django 3.2.13 on 2022-04-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_genre_musicproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicproduct',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Track description'),
        ),
    ]
