# Generated by Django 3.2.13 on 2022-04-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_musicproduct_track_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicproduct',
            name='track_category',
        ),
        migrations.AddField(
            model_name='musicproduct',
            name='track_category',
            field=models.ManyToManyField(to='core.Category', verbose_name='Track category'),
        ),
    ]
