# Generated by Django 3.2.13 on 2022-04-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220428_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicproduct',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Color background'),
        ),
    ]
