# Generated by Django 3.2.13 on 2022-04-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_musicproduct_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicproduct',
            name='color',
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Color background'),
        ),
    ]
