# Generated by Django 3.2.13 on 2022-05-08 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220429_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='image',
        ),
    ]
