# Generated by Django 3.2.13 on 2022-05-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_genre_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='image_genre',
            field=models.ImageField(blank=True, null=True, upload_to='img_genre/', verbose_name='Imagine'),
        ),
    ]
