# Generated by Django 3.2.13 on 2022-05-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_genre_image_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='image_genre',
        ),
        migrations.AddField(
            model_name='genre',
            name='image',
            field=models.ImageField(blank=True, default='/img/default.jpg', null=True, upload_to='img_genre/', verbose_name='Imagine'),
        ),
    ]
