# Generated by Django 3.2.13 on 2022-05-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220511_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='image',
            field=models.ImageField(default='/music_app/core/static/core/img/default.jpg', upload_to='img_genre/', verbose_name='Imagine'),
        ),
    ]
