# Generated by Django 3.2.13 on 2022-05-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_genre_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='image',
            field=models.ImageField(default='/img/default.jpg', upload_to='img_genre/', verbose_name='Imagine'),
        ),
    ]
