# Generated by Django 3.2.13 on 2022-06-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_genre_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.TextField(blank=True, null=True, verbose_name='Color background'),
        ),
    ]
