# Generated by Django 3.2.13 on 2022-06-16 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='data',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Date added'),
        ),
    ]
