# Generated by Django 3.2.13 on 2022-06-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20220618_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicproduct',
            name='category',
            field=models.ManyToManyField(db_table='all_category', to='core.Category', verbose_name='Track category'),
        ),
        migrations.AlterField(
            model_name='musicproduct',
            name='genre',
            field=models.ManyToManyField(db_table='all_genre', to='core.Genre', verbose_name='All genre'),
        ),
    ]
