# Generated by Django 3.2.13 on 2022-06-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20220618_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicproduct',
            name='category',
            field=models.ManyToManyField(db_column='all_category', to='core.Category', verbose_name='Track category'),
        ),
        migrations.AlterField(
            model_name='musicproduct',
            name='genre',
            field=models.ManyToManyField(db_column='all_genre', to='core.Genre', verbose_name='All genre'),
        ),
    ]
