# Generated by Django 3.2.13 on 2022-06-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20220618_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicproduct',
            name='duration_track',
            field=models.CharField(default='0:00', max_length=255, verbose_name='Duration track'),
        ),
    ]
