# Generated by Django 3.2.13 on 2022-06-30 13:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0024_musicproduct_all_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name playlist')),
                ('imagen', models.ImageField(default='music_icon.svg', upload_to='img_playlist/', verbose_name='Image for playlist')),
                ('date', models.DateField(default=datetime.datetime.today, verbose_name='Date create')),
                ('track', models.ManyToManyField(to='core.MusicProduct', verbose_name='Track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
        ),
    ]
