# Generated by Django 3.2.13 on 2022-06-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_playlist_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='playlist',
            field=models.ManyToManyField(to='core.Playlist', verbose_name='All playlists'),
        ),
    ]
