# Generated by Django 3.2.13 on 2022-06-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_customer_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicproduct',
            name='all_like',
            field=models.ManyToManyField(to='core.Like', verbose_name='All like'),
        ),
    ]
