# Generated by Django 3.2.13 on 2022-06-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20220630_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='imagen',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='track',
            field=models.ManyToManyField(blank=True, to='core.MusicProduct', verbose_name='Track'),
        ),
    ]
