# Generated by Django 3.2.13 on 2022-06-30 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20220630_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='playlist',
            new_name='all_playlist',
        ),
    ]
