# Generated by Django 3.2.13 on 2022-06-30 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_rename_playlist_customer_all_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_playlist+', to='core.playlist', verbose_name='Playlist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.musicproduct', verbose_name='Name track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer', verbose_name='Customer')),
            ],
        ),
    ]
