# Generated by Django 3.2.13 on 2022-06-30 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_playlisttrack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='track',
            field=models.ManyToManyField(blank=True, related_name='_core_playlist_track_+', to='core.PlaylistTrack', verbose_name='Track'),
        ),
        migrations.AlterField(
            model_name='playlisttrack',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.playlist', verbose_name='Customer playlist'),
        ),
    ]
