# Generated by Django 3.2.13 on 2022-07-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20220630_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicproduct',
            name='bitrate',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bitrate'),
        ),
        migrations.AddField(
            model_name='musicproduct',
            name='format',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Format'),
        ),
        migrations.AddField(
            model_name='musicproduct',
            name='size_file',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Size file'),
        ),
    ]
