# Generated by Django 3.2.13 on 2022-08-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20220731_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='color',
            field=models.TextField(blank=True, null=True, verbose_name='Playlist background color'),
        ),
    ]
