# Generated by Django 3.2.13 on 2022-08-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_playlist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='image',
            field=models.ImageField(default='img_playlist/music_icon.svg', upload_to='img_playlist/', verbose_name='Image for playlist'),
        ),
    ]
